#!/usr/bin/env python3

import argparse
import hashlib
import html
import re
import shutil
import sys
import yaml
from pathlib import Path
from typing import Any
from urllib.parse import quote, unquote, urljoin, urlparse
from urllib.request import Request, urlopen


DOWNLOAD_BASE_URL = 'https://files1.youxuepai.com/Upload/'
USER_AGENT = 'np-upgrade-resource-list/1.0'


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Sync Noah model resources from YAML to the local directory.',
    )
    parser.add_argument('input', nargs='?', default='-', help='YAML file generated by noah-get.py (reads from stdin if omitted).')
    parser.add_argument('--compact', action='store_true', help='Use compact format for the generated markdown meta files.')
    parser.add_argument('--verify-md5', action='store_true', help='Verify MD5 checksum for existing files (can be slow for large files).')
    parser.add_argument('--verbose', action='store_true', help='Print detailed progress to stderr.')
    return parser.parse_args()


def normalize_name(value: object) -> str:
    return ' '.join(str(value or '').split()).lower()


def escape_markdown(value: object) -> str:
    return re.sub(r'([\\`*_[\]<>])', r'\\\1', str(value or ''))


def decode_html(value: object) -> str:
    text = str(value or '')
    text = re.sub(r'<\s*br\s*/?\s*>', '\n', text, flags=re.IGNORECASE)
    text = re.sub(r'</?p\s*>', '\n', text, flags=re.IGNORECASE)
    text = re.sub(r'<[^>]*>', '', text)
    text = html.unescape(text).replace('\r', '')
    return re.sub(r'\n[ \t]*\n+', '\n', text).strip()


def download_url(resource: dict[str, Any]) -> str:
    source_address = resource.get('souraddr')
    if source_address:
        return urljoin(DOWNLOAD_BASE_URL, quote(str(source_address), safe='/'))
    return resource.get('url') or f"http://dl.youxuepai.com/download/courseware/{resource['id']}"


def resource_name(resource: dict[str, Any]) -> str:
    return str(resource.get('cname') or resource.get('name') or resource.get('fileName') or '')


def resource_markdown(resource: dict[str, Any], compact: bool) -> str:
    fields = [
        ('资源 ID', resource.get('id')),
        ('类别', resource.get('type')),
        ('大小', resource.get('sfileSize')),
        ('更新日期', resource.get('updateTime')),
        ('科目', resource.get('subject')),
        ('年级', resource.get('gradeFull') or resource.get('grade')),
        ('学期', resource.get('term')),
        ('出版社', resource.get('publishname') or resource.get('press')),
        ('版本', resource.get('version') or resource.get('revision')),
        ('适用机型', resource.get('products')),
        ('MD5', resource.get('md5Code')),
    ]
    if compact:
        fields = [
            ('大小', resource.get('sfileSize')),
            ('更新日期', resource.get('updateTime')),
            ('MD5', resource.get('md5Code')),
        ]
    lines = [f"- **{escape_markdown(resource_name(resource))}**"]

    for label, value in fields:
        if value not in (None, ''):
            lines.append(f'  - {label}: {escape_markdown(value)}')

    if not compact:
        description = decode_html(resource.get('description') or resource.get('remarks'))
        if description:
            lines.append('  - 说明:')
            lines.extend(f'    - {escape_markdown(paragraph.strip())}' for paragraph in description.split('\n') if paragraph)

    lines.append(f'  - 下载: <{download_url(resource)}>')
    return '\n'.join(lines)


def verify_md5(file_path: Path, expected_md5: str) -> bool:
    if not expected_md5:
        return True
    hash_md5 = hashlib.md5()
    try:
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(1024 * 1024), b""):
                hash_md5.update(chunk)
        return hash_md5.hexdigest().lower() == expected_md5.lower()
    except Exception:
        return False


def download_resource(resource: dict[str, Any], download_dir: Path, verbose: bool, compact: bool, verify_md5_flag: bool) -> None:
    url = download_url(resource)
    parsed_url = urlparse(url)
    rel_path = unquote(parsed_url.path.lstrip('/'))
    file_path = download_dir / rel_path
    
    needs_download = True
    if file_path.exists():
        expected_md5 = resource.get('md5Code')
        if not expected_md5 or not verify_md5_flag:
            if verbose:
                reason = "MD5 verification disabled" if verify_md5_flag is False else "no MD5 provided"
                print(f"Skipping existing file ({reason}): {file_path}", file=sys.stderr)
            needs_download = False
        else:
            if verbose:
                print(f"Verifying MD5 for {file_path}...", file=sys.stderr)
            if verify_md5(file_path, expected_md5):
                if verbose:
                    print(f"MD5 matches, skipping: {file_path}", file=sys.stderr)
                needs_download = False
            else:
                if verbose:
                    print(f"MD5 mismatch for {file_path}, redownloading...", file=sys.stderr)

    if needs_download:
        print(f"Downloading {url} to {file_path}", file=sys.stderr)
        file_path.parent.mkdir(parents=True, exist_ok=True)
        temp_file_path = file_path.with_name(file_path.name + '.downloading')
        
        try:
            request = Request(url, headers={'User-Agent': USER_AGENT})
            with urlopen(request, timeout=600) as response, temp_file_path.open('wb') as out_file:
                shutil.copyfileobj(response, out_file)
            temp_file_path.rename(file_path)
        except Exception as error:
            print(f"Failed to download {url}: {error}", file=sys.stderr)
            if temp_file_path.exists():
                temp_file_path.unlink()
            return
        except KeyboardInterrupt:
            print(f"\nDownload interrupted. Cleaning up {temp_file_path}", file=sys.stderr)
            if temp_file_path.exists():
                temp_file_path.unlink()
            raise

    meta_path = file_path.with_name(file_path.name + '.md')
    with meta_path.open('w', encoding='utf-8') as f:
        f.write(resource_markdown(resource, compact) + '\n')


def sync_catalog_tree(
    nodes: list[dict[str, Any]],
    download_dir: Path,
    verbose: bool,
    compact: bool,
    verify_md5_flag: bool,
) -> None:
    for node in nodes:
        children = node.get('children') or []
        if children:
            sync_catalog_tree(children, download_dir, verbose, compact, verify_md5_flag)
        else:
            resources = node.get('resources', [])
            for resource in resources:
                download_resource(resource, download_dir, verbose, compact, verify_md5_flag)


def main() -> None:
    options = parse_arguments()
    
    if options.input == '-':
        content = sys.stdin.read()
        if not content.strip():
            sys.exit(1)
        data = yaml.safe_load(content)
    else:
        with open(options.input, 'r', encoding='utf-8') as f:
            data = yaml.safe_load(f)

    catalogs = data.get('catalogs', [])
    download_dir = Path('.')
    
    print("Starting sync to current directory...", file=sys.stderr)
    sync_catalog_tree(catalogs, download_dir, options.verbose, options.compact, options.verify_md5)
    print("Sync complete.", file=sys.stderr)


if __name__ == '__main__':
    try:
        main()
    except Exception as error:
        print(f'Error: {error}', file=sys.stderr)
        sys.exit(1)
