#!/usr/bin/env python3

import argparse
import html
import re
import sys
import yaml
from pathlib import Path
from typing import Any, TextIO
from urllib.parse import quote, unquote, urljoin, urlparse


DOWNLOAD_BASE_URL = 'https://files1.youxuepai.com/Upload/'


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Render Noah model resources from YAML to Markdown.',
    )
    parser.add_argument('input', help='YAML file generated by noah-get.py, or "-" to read from stdin.')
    parser.add_argument('--compact', action='store_true', help='Only output file names, size, date, MD5, and download URLs.')
    parser.add_argument('--out', metavar='FILE', help='Write Markdown to FILE instead of stdout.')
    return parser.parse_args()


def normalize_name(value: object) -> str:
    return ' '.join(str(value or '').split()).lower()


def escape_markdown(value: object) -> str:
    return re.sub(r'([\\`*_[\]<>])', r'\\\1', str(value or ''))


def decode_html(value: object) -> str:
    text = str(value or '')
    text = re.sub(r'<\s*br\s*/?\s*>', '\n', text, flags=re.IGNORECASE)
    text = re.sub(r'</?p\s*>', '\n', text, flags=re.IGNORECASE)
    text = re.sub(r'<[^>]*>', '', text)
    text = html.unescape(text).replace('\r', '')
    return re.sub(r'\n[ \t]*\n+', '\n', text).strip()


def download_url(resource: dict[str, Any]) -> str:
    source_address = resource.get('souraddr')
    if source_address:
        return urljoin(DOWNLOAD_BASE_URL, quote(str(source_address), safe='/'))
    return resource.get('url') or f"http://dl.youxuepai.com/download/courseware/{resource['id']}"


def resource_name(resource: dict[str, Any]) -> str:
    return str(resource.get('cname') or resource.get('name') or resource.get('fileName') or '')


def resource_markdown(resource: dict[str, Any], compact: bool) -> str:
    fields = [
        ('资源 ID', resource.get('id')),
        ('类别', resource.get('type')),
        ('大小', resource.get('sfileSize')),
        ('更新日期', resource.get('updateTime')),
        ('科目', resource.get('subject')),
        ('年级', resource.get('gradeFull') or resource.get('grade')),
        ('学期', resource.get('term')),
        ('出版社', resource.get('publishname') or resource.get('press')),
        ('版本', resource.get('version') or resource.get('revision')),
        ('适用机型', resource.get('products')),
        ('MD5', resource.get('md5Code')),
    ]
    if compact:
        fields = [
            ('大小', resource.get('sfileSize')),
            ('更新日期', resource.get('updateTime')),
            ('MD5', resource.get('md5Code')),
        ]
    lines = [f"- **{escape_markdown(resource_name(resource))}**"]

    for label, value in fields:
        if value not in (None, ''):
            lines.append(f'  - {label}: {escape_markdown(value)}')

    if not compact:
        description = decode_html(resource.get('description') or resource.get('remarks'))
        if description:
            lines.append('  - 说明:')
            lines.extend(f'    - {escape_markdown(paragraph.strip())}' for paragraph in description.split('\n') if paragraph)

    lines.append(f'  - 下载: <{download_url(resource)}>')
    return '\n'.join(lines)


def write(output: TextIO, content: str) -> None:
    output.write(content)
    output.flush()


def write_catalog_markdown(
    nodes: list[dict[str, Any]],
    output: TextIO,
    compact: bool,
    depth: int = 3,
    skip_root_heading: bool = False,
) -> None:
    for index, node in enumerate(nodes):
        children = node.get('children') or []
        if not (skip_root_heading and depth == 3 and index == 0):
            heading = '#' * min(depth, 6)
            write(output, f"{heading} {escape_markdown(str(node.get('name', '')).strip())}\n\n")

        if children:
            write_catalog_markdown(children, output, compact, depth + 1)
        else:
            resources = node.get('resources', [])
            for resource in resources:
                write(output, f'{resource_markdown(resource, compact)}\n')
            write(output, '\n')


def main() -> None:
    options = parse_arguments()
    
    if options.input == '-':
        content = sys.stdin.read()
        if not content.strip():
            sys.exit(1)
        data = yaml.safe_load(content)
    else:
        with open(options.input, 'r', encoding='utf-8') as f:
            data = yaml.safe_load(f)

    product = data.get('product', {})
    catalogs = data.get('catalogs', [])
    site_url = data.get('site_url', 'https://downloads.youxuepai.com/source/list.shtml')
    
    skip_root_heading = len(catalogs) == 1 and not catalogs[0].get('children')

    output: TextIO = sys.stdout
    output_file: TextIO | None = None

    if options.out:
        output_path = Path(options.out)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_file = output_path.open('w', encoding='utf-8')
        output = output_file

    try:
        if not options.compact:
            product_id = product.get('id', '')
            product_name = product.get('name', '')
            write(output, '\n'.join([
                f"# {escape_markdown(product_name)} 资源下载清单",
                '',
                f"- 产品 ID: {product_id}",
                f"- 资源页: <{site_url}#{product_id}>",
                '',
                '## 功能目录',
                '',
            ]))
        write_catalog_markdown(
            catalogs,
            output,
            options.compact,
            skip_root_heading=skip_root_heading,
        )
    finally:
        if output_file:
            output_file.close()


if __name__ == '__main__':
    try:
        main()
    except Exception as error:
        print(f'Error: {error}', file=sys.stderr)
        sys.exit(1)
